version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - prime_coherence_data:/app/artifacts
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build: ./frontend
    environment:
      - API_BASE_URL=http://api:8000
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      api:
        condition: service_healthy

volumes:
  prime_coherence_data:
